name: quran_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.4
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  scrollable_positioned_list: ^0.3.8
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  archive: ^4.0.7
  hugeicons:
    hosted: https://onepub.dev/api/kdpxxpsdav/
    version: ^0.0.12
  quran: ^1.3.3
  share_plus: ^11.0.0
  flutter_screenutil: ^5.9.3
  scroll_to_index: ^3.0.1
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.6
  sqflite: ^2.4.2
  huge_listview: ^2.0.12
  draggable_scrollbar: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  device_preview: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/image/front_page/
  fonts:
    - family: SolaimanLipi
      fonts:
        - asset: fonts/Bangla Fonts/Solaimanlipi.ttf
    - family: Kalpurush
      fonts:
        - asset: fonts/Bangla Fonts/Kalpurush.ttf
    - family: Noto Sans Bengali
      fonts:
        - asset: fonts/Bangla Fonts/Noto Sans Bengali.ttf
    - family: Siyam Rupali
      fonts:
        - asset: fonts/Bangla Fonts/Siyam Rupali.ttf

    - family: Al Mushaf Quran
      fonts:
        - asset: fonts/Arabic Fonts/Al Mushaf Quran.ttf
    - family: Al Qalam Kolkatta Quranic
      fonts:
        - asset: fonts/Arabic Fonts/Al Qalam Kolkatta Quranic.ttf
    - family: Al Qalam Quran
      fonts:
        - asset: fonts/Arabic Fonts/Al Qalam Quran.ttf
    - family: Al Qalam Quran Majeed
      fonts:
        - asset: fonts/Arabic Fonts/Al Qalam Quran Majeed.ttf