import '../sura_list_item.dart';

const List<SuraListItemModel> allSuras = [
  SuraListItemModel(number: 1, nameBangla: 'আল ফাতিহা', meaningBangla: 'সূচনা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ ٱلْفَاتِحَةِ'),
  SuraListItemModel(number: 2, nameBangla: 'আল বাকারা', meaningBangla: 'গাভী', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْبَقَرَةِ'),
  SuraListItemModel(number: 3, nameBangla: 'আল ইমরান', meaningBangla: 'ইমরানের পরিবার', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ آلِ عِمْرَانَ'),
  SuraListItemModel(number: 4, nameBangla: 'আন নিসা', meaningBangla: 'নারী', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ النِّسَاءِ'),
  SuraListItemModel(number: 5, nameBangla: 'আল মায়িদাহ', meaningBangla: 'খাদ্য পরিবেশিত টেবিল', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْمَائِدَةِ'),
  SuraListItemModel(number: 6, nameBangla: 'আল আনআম', meaningBangla: 'গৃহপালিত পশু', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْأَنْعَامِ'),
  SuraListItemModel(number: 7, nameBangla: 'আল আরাফ', meaningBangla: 'উচু স্থান', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْأَعْرَافِ'),
  SuraListItemModel(number: 8, nameBangla: 'আল আনফাল', meaningBangla: 'যুদ্ধলব্ধ সম্পদ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْأَنْفَالِ'),
  SuraListItemModel(number: 9, nameBangla: 'আত তাওবাহ', meaningBangla: 'অনুশোচনা', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ التَّوْبَةِ'),
  SuraListItemModel(number: 10, nameBangla: 'ইউনুস', meaningBangla: 'একজন নবীর নাম', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ يُونُسَ'),
  SuraListItemModel(number: 11, nameBangla: 'হুদ', meaningBangla: 'একজন নবীর নাম', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ هُودٍ'),
  SuraListItemModel(number: 12, nameBangla: 'ইউসুফ', meaningBangla: 'একজন নবীর নাম', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ يُوسُفَ'),
  SuraListItemModel(number: 13, nameBangla: 'আর রাদ', meaningBangla: 'বজ্রনাদ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الرَّعْدِ'),
  SuraListItemModel(number: 14, nameBangla: 'ইবরাহীম', meaningBangla: 'একজন নবীর নাম', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ إِبْرَاهِيمَ'),
  SuraListItemModel(number: 15, nameBangla: 'আল হিজর', meaningBangla: 'পাথুরে ভূমি', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْحِجْرِ'),
  SuraListItemModel(number: 16, nameBangla: 'আন নাহল', meaningBangla: 'মৌমাছি', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ النَّحْلِ'),
  SuraListItemModel(number: 17, nameBangla: 'আল ইসরা', meaningBangla: 'রাতের ভ্রমণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْإِسْرَاءِ'),
  SuraListItemModel(number: 18, nameBangla: 'আল কাহফ', meaningBangla: 'গুহা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْكَهْفِ'),
  SuraListItemModel(number: 19, nameBangla: 'মারইয়াম', meaningBangla: 'ঈসা (আঃ) এর মা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ مَرْيَمَ'),
  SuraListItemModel(number: 20, nameBangla: 'ত্ব-হা', meaningBangla: 'ত্ব-হা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ طه'),
  SuraListItemModel(number: 21, nameBangla: 'আল আম্বিয়া', meaningBangla: 'নবীগণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْأَنْبِيَاءِ'),
  SuraListItemModel(number: 22, nameBangla: 'আল হাজ্জ', meaningBangla: 'হজ্জ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْحَجِّ'),
  SuraListItemModel(number: 23, nameBangla: 'আল মুমিনুন', meaningBangla: 'মুমিনগণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْمُؤْمِنُونَ'),
  SuraListItemModel(number: 24, nameBangla: 'আন নূর', meaningBangla: 'আলো', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ النُّورِ'),
  SuraListItemModel(number: 25, nameBangla: 'আল ফুরকান', meaningBangla: 'সত্য মিথ্যার পার্থক্যকারী', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْفُرْقَانِ'),
  SuraListItemModel(number: 26, nameBangla: 'আশ শুআরা', meaningBangla: 'কবিগণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الشُّعَرَاءِ'),
  SuraListItemModel(number: 27, nameBangla: 'আন নামল', meaningBangla: 'পিপীলিকা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ النَّمْلِ'),
  SuraListItemModel(number: 28, nameBangla: 'আল কাসাস', meaningBangla: 'কাহিনী', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْقَصَصِ'),
  SuraListItemModel(number: 29, nameBangla: 'আল আনকাবুত', meaningBangla: 'মাকড়সা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْعَنْكَبُوتِ'),
  SuraListItemModel(number: 30, nameBangla: 'আর রুম', meaningBangla: 'রোমান জাতি', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الرُّومِ'),
  SuraListItemModel(number: 31, nameBangla: 'লুকমান', meaningBangla: 'একজন জ্ঞানী ব্যক্তি', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ لُقْمَانَ'),
  SuraListItemModel(number: 32, nameBangla: 'আস সেজদাহ', meaningBangla: 'সিজদা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ السَّجْدَةِ'),
  SuraListItemModel(number: 33, nameBangla: 'আল আহযাব', meaningBangla: 'জোট', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْأَحْزَابِ'),
  SuraListItemModel(number: 34, nameBangla: 'সাবা', meaningBangla: 'রানী সাবা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ سَبَأٍ'),
  SuraListItemModel(number: 35, nameBangla: 'ফাতির', meaningBangla: 'আদি স্রষ্টা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ فَاطِرٍ'),
  SuraListItemModel(number: 36, nameBangla: 'ইয়াসীন', meaningBangla: 'ইয়াসীন', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ يس'),
  SuraListItemModel(number: 37, nameBangla: 'আস ছাফফাত', meaningBangla: 'সারিবদ্ধভাবে দাঁড়ানো', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الصَّافَّاتِ'),
  SuraListItemModel(number: 38, nameBangla: 'ছোয়াদ', meaningBangla: 'আরবি বর্ণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ ص'),
  SuraListItemModel(number: 39, nameBangla: 'আয যুমার', meaningBangla: 'দলবদ্ধ জনতা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الزُّمَرِ'),
  SuraListItemModel(number: 40, nameBangla: 'গাফির', meaningBangla: 'ক্ষমাকারী', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ غَافِرٍ'),
  SuraListItemModel(number: 41, nameBangla: 'ফুসসিলাত', meaningBangla: 'বিস্তারিতভাবে বর্ণিত', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ فُصِّلَتْ'),
  SuraListItemModel(number: 42, nameBangla: 'আশ শূরা', meaningBangla: 'পরামর্শ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الشُّورَىٰ'),
  SuraListItemModel(number: 43, nameBangla: 'আয যুখরুফ', meaningBangla: 'স্বর্ণালংকার', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الزُّخْرُفِ'),
  SuraListItemModel(number: 44, nameBangla: 'আদ দুখান', meaningBangla: 'ধোঁয়া', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الدُّخَانِ'),
  SuraListItemModel(number: 45, nameBangla: 'আল জাসিয়াহ', meaningBangla: 'নতজানু', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْجَاثِيَةِ'),
  SuraListItemModel(number: 46, nameBangla: 'আল আহকাফ', meaningBangla: 'বালিয়াড়ি', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْأَحْقَافِ'),
  SuraListItemModel(number: 47, nameBangla: 'মুহাম্মদ', meaningBangla: 'একজন নবীর নাম', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ مُحَمَّدٍ'),
  SuraListItemModel(number: 48, nameBangla: 'আল ফাতহ', meaningBangla: 'বিজয়', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْفَتْحِ'),
  SuraListItemModel(number: 49, nameBangla: 'আল হুজুরাত', meaningBangla: 'বাসগৃহসমূহ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْحُجُرَاتِ'),
  SuraListItemModel(number: 50, nameBangla: 'ক্বাফ', meaningBangla: 'আরবি বর্ণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ ق'),
  SuraListItemModel(number: 51, nameBangla: 'আয যারিয়াত', meaningBangla: 'বিক্ষেপকারী বাতাস', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الذَّارِيَاتِ'),
  SuraListItemModel(number: 52, nameBangla: 'আত তুর', meaningBangla: 'তুর পর্বত', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الطُّورِ'),
  SuraListItemModel(number: 53, nameBangla: 'আন নাজম', meaningBangla: 'তারা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ النَّجْمِ'),
  SuraListItemModel(number: 54, nameBangla: 'আল ক্বামার', meaningBangla: 'চন্দ্র', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْقَمَرِ'),
  SuraListItemModel(number: 55, nameBangla: 'আর রাহমান', meaningBangla: 'পরম করুণাময়', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الرَّحْمَٰنِ'),
  SuraListItemModel(number: 56, nameBangla: 'আল ওয়াক্বিয়াহ', meaningBangla: 'অবশ্যম্ভাবী ঘটনা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْوَاقِعَةِ'),
  SuraListItemModel(number: 57, nameBangla: 'আল হাদীদ', meaningBangla: 'লৌহ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْحَدِيدِ'),
  SuraListItemModel(number: 58, nameBangla: 'আল মুজাদালাহ', meaningBangla: 'অনুযোগকারিণী', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْمُجَادَلَةِ'),
  SuraListItemModel(number: 59, nameBangla: 'আল হাশর', meaningBangla: 'সমাবেশ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْحَشْرِ'),
  SuraListItemModel(number: 60, nameBangla: 'আল মুমতাহানাহ', meaningBangla: 'নারী, যাকে পরীক্ষা করা হবে', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْمُمْتَحَنَةِ'),
  SuraListItemModel(number: 61, nameBangla: 'আস সাফ', meaningBangla: 'সারিবদ্ধ সৈন্যদল', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الصَّفِّ'),
  SuraListItemModel(number: 62, nameBangla: 'আল জুমুআহ', meaningBangla: 'জমায়েত হওয়ার দিন', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْجُمُعَةِ'),
  SuraListItemModel(number: 63, nameBangla: 'আল মুনাফিকুন', meaningBangla: 'কপট বিশ্বাসীগণ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْمُنَافِقُونَ'),
  SuraListItemModel(number: 64, nameBangla: 'আত তাগাবুন', meaningBangla: 'মোহ অপসারণ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ التَّغَابُنِ'),
  SuraListItemModel(number: 65, nameBangla: 'আত ত্বালাক', meaningBangla: 'তালাক', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الطَّلَاقِ'),
  SuraListItemModel(number: 66, nameBangla: 'আত তাহরীম', meaningBangla: 'নিষিদ্ধকরণ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ التَّحْرِيمِ'),
  SuraListItemModel(number: 67, nameBangla: 'আল মুলক', meaningBangla: 'সার্বভৌম কর্তৃত্ব', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْمُلْكِ'),
  SuraListItemModel(number: 68, nameBangla: 'আল ক্বলম', meaningBangla: 'কলম', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْقَلَمِ'),
  SuraListItemModel(number: 69, nameBangla: 'আল হাক্কাহ', meaningBangla: 'নিশ্চিত সত্য', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْحَاقَّةِ'),
  SuraListItemModel(number: 70, nameBangla: 'আল মাআরিজ', meaningBangla: 'উন্নয়নের সোপান', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْمَعَارِجِ'),
  SuraListItemModel(number: 71, nameBangla: 'নূহ', meaningBangla: 'একজন নবীর নাম', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ نُوحٍ'),
  SuraListItemModel(number: 72, nameBangla: 'আল জ্বিন', meaningBangla: 'জিন জাতি', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْجِنِّ'),
  SuraListItemModel(number: 73, nameBangla: 'আল মুযযাম্মিল', meaningBangla: 'বস্ত্রাচ্ছাদনকারী', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْمُزَّمِّلِ'),
  SuraListItemModel(number: 74, nameBangla: 'আল মুদ্দাসসির', meaningBangla: 'পোশাক পরিহিত', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْمُدَّثِّرِ'),
  SuraListItemModel(number: 75, nameBangla: 'আল ক্বিয়ামাহ', meaningBangla: 'পুনরুত্থান', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْقِيَامَةِ'),
  SuraListItemModel(number: 76, nameBangla: 'আল ইনসান', meaningBangla: 'মানুষ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْإِنْسَانِ'),
  SuraListItemModel(number: 77, nameBangla: 'আল মুরসালাত', meaningBangla: 'প্রেরিত পুরুষগণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْمُرْسَلَاتِ'),
  SuraListItemModel(number: 78, nameBangla: 'আন নাবা', meaningBangla: 'মহা সংবাদ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ النَّبَإِ'),
  SuraListItemModel(number: 79, nameBangla: 'আন নাযিয়াত', meaningBangla: 'প্রচেষ্টাকারী', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ النَّازِعَاتِ'),
  SuraListItemModel(number: 80, nameBangla: 'আবাসা', meaningBangla: 'তিনি ভ্রুকুটি করলেন', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ عَبَسَ'),
  SuraListItemModel(number: 81, nameBangla: 'আত তাকওয়ীর', meaningBangla: 'অন্ধকারাচ্ছন্ন', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ التَّكْوِيرِ'),
  SuraListItemModel(number: 82, nameBangla: 'আল ইনফিতার', meaningBangla: 'বিদীর্ণ হওয়া', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الِانْفِطَارِ'),
  SuraListItemModel(number: 83, nameBangla: 'আল মুতাফফিফীন', meaningBangla: 'প্রতারণা করা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْمُطَفِّفِينَ'),
  SuraListItemModel(number: 84, nameBangla: 'আল ইনশিকাক', meaningBangla: 'খন্ড-বিখন্ড করণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الِانْشِقَاقِ'),
  SuraListItemModel(number: 85, nameBangla: 'আল বুরূজ', meaningBangla: 'নক্ষত্রপুঞ্জ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْبُرُوجِ'),
  SuraListItemModel(number: 86, nameBangla: 'আত তারিক', meaningBangla: 'রাতের আগন্তুক', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الطَّارِقِ'),
  SuraListItemModel(number: 87, nameBangla: 'আল আলা', meaningBangla: 'সর্বোচ্চ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْأَعْلَىٰ'),
  SuraListItemModel(number: 88, nameBangla: 'আল গাশিয়াহ', meaningBangla: 'আচ্ছন্নকারী', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْغَاشِيَةِ'),
  SuraListItemModel(number: 89, nameBangla: 'আল ফাজর', meaningBangla: 'ভোরবেলা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْفَجْرِ'),
  SuraListItemModel(number: 90, nameBangla: 'আল বালাদ', meaningBangla: 'নগর', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْبَلَدِ'),
  SuraListItemModel(number: 91, nameBangla: 'আশ শামস', meaningBangla: 'সূর্য', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الشَّمْسِ'),
  SuraListItemModel(number: 92, nameBangla: 'আল লাইল', meaningBangla: 'রাত্রি', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ اللَّيْلِ'),
  SuraListItemModel(number: 93, nameBangla: 'আদ দুহা', meaningBangla: 'পূর্বাহ্নের সুর্যকিরণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الضُّحَىٰ'),
  SuraListItemModel(number: 94, nameBangla: 'আশ শারহ', meaningBangla: 'প্রশস্তকরণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الشَّرْحِ'),
  SuraListItemModel(number: 95, nameBangla: 'আত তীন', meaningBangla: 'ডুমুর', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ التِّينِ'),
  SuraListItemModel(number: 96, nameBangla: 'আল আলাক', meaningBangla: 'রক্তপিন্ড', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْعَلَقِ'),
  SuraListItemModel(number: 97, nameBangla: 'আল কদর', meaningBangla: 'মহিমান্বিত', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْقَدْرِ'),
  SuraListItemModel(number: 98, nameBangla: 'আল বাইয়্যিনাহ', meaningBangla: 'সুস্পষ্ট প্রমাণ', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الْبَيِّنَةِ'),
  SuraListItemModel(number: 99, nameBangla: 'আয যিলযাল', meaningBangla: 'ভূমিকম্প', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ الزَّلْزَلَةِ'),
  SuraListItemModel(number: 100, nameBangla: 'আল আদিয়াত', meaningBangla: 'অভিযানকারী', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْعَادِيَاتِ'),
  SuraListItemModel(number: 101, nameBangla: 'আল ক্বারিয়াহ', meaningBangla: 'মহাসংকট', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْقَارِعَةِ'),
  SuraListItemModel(number: 102, nameBangla: 'আত তাকাসুর', meaningBangla: 'প্রাচুর্যের প্রতিযোগিতা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ التَّكَاثُرِ'),
  SuraListItemModel(number: 103, nameBangla: 'আল আসর', meaningBangla: 'সময়', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْعَصْرِ'),
  SuraListItemModel(number: 104, nameBangla: 'আল হুমাযাহ', meaningBangla: 'পরনিন্দাকারী', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْهُمَزَةِ'),
  SuraListItemModel(number: 105, nameBangla: 'আল ফীল', meaningBangla: 'হাতি', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْفِيلِ'),
  SuraListItemModel(number: 106, nameBangla: 'কুরাইশ', meaningBangla: 'কুরাইশ গোত্র', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ قُرَيْشٍ'),
  SuraListItemModel(number: 107, nameBangla: 'আল মাউন', meaningBangla: 'নিত্য ব্যবহার্য সামগ্রী', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْمَاعُونِ'),
  SuraListItemModel(number: 108, nameBangla: 'আল কাউসার', meaningBangla: 'প্রাচুর্য', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْكَوْثَرِ'),
  SuraListItemModel(number: 109, nameBangla: 'আল কাফিরুন', meaningBangla: 'অবিশ্বাসীগণ', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْكَافِرُونَ'),
  SuraListItemModel(number: 110, nameBangla: 'আন নাসর', meaningBangla: 'সাহায্য', revelationType: RevelationType.Madani, nameArabic: 'سُورَةُ النَّصْرِ'),
  SuraListItemModel(number: 111, nameBangla: 'আল মাসাদ', meaningBangla: 'তাবা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْمَسَدِ'),
  SuraListItemModel(number: 112, nameBangla: 'আল ইখলাস', meaningBangla: 'একনিষ্ঠতা', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْإِخْلَاصِ'),
  SuraListItemModel(number: 113, nameBangla: 'আল ফালাক', meaningBangla: 'নিশিভোর', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ الْفَلَقِ'),
  SuraListItemModel(number: 114, nameBangla: 'আন নাস', meaningBangla: 'মানবজাতি', revelationType: RevelationType.Makki, nameArabic: 'سُورَةُ النَّاسِ'),
];